"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var like_component_1 = require("./like.component");
var component = new like_component_1.LikeComponent(10, true);
var likesCount = component.likesCount;
var isSelected = component.isSelected;
console.log('Initial number of likes: ' + likesCount);
console.log('Initial like button isSelected: ' + isSelected);
console.log('click like');
component.onClick();
likesCount = component.likesCount;
isSelected = component.isSelected;
console.log('Final number of likes: ' + likesCount);
console.log('Final like button isSelected: ' + isSelected);
console.log('click like');
component.onClick();
likesCount = component.likesCount;
isSelected = component.isSelected;
console.log('Final number of likes: ' + likesCount);
console.log('Final like button isSelected: ' + isSelected);
